// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDtYBZZDx6Pzi7zspD1I-F8PomtvvBiIY',
    appId: '1:198267727107:web:e97369c81209406a9ecd36',
    messagingSenderId: '198267727107',
    projectId: 'fir-flutter-codelab-7fe8e',
    authDomain: 'fir-flutter-codelab-7fe8e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7fe8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZzxM276pojkUqaB5h0GrCrkz2Cb5efE',
    appId: '1:198267727107:android:b7c139548f323ba89ecd36',
    messagingSenderId: '198267727107',
    projectId: 'fir-flutter-codelab-7fe8e',
    storageBucket: 'fir-flutter-codelab-7fe8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjybZvhjFB-n7JCWiiGYkIn_hy6S3PZUs',
    appId: '1:198267727107:ios:6797abc493bd59499ecd36',
    messagingSenderId: '198267727107',
    projectId: 'fir-flutter-codelab-7fe8e',
    storageBucket: 'fir-flutter-codelab-7fe8e.appspot.com',
    iosClientId:
        '198267727107-c75v1rahvhaprhj7fmfj86drhn4dm4fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.qcFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjybZvhjFB-n7JCWiiGYkIn_hy6S3PZUs',
    appId: '1:198267727107:ios:96ecbc4db1654c899ecd36',
    messagingSenderId: '198267727107',
    projectId: 'fir-flutter-codelab-7fe8e',
    storageBucket: 'fir-flutter-codelab-7fe8e.appspot.com',
    iosClientId:
        '198267727107-9te2bj8enciocgi3e2rpa9p8se8n0spv.apps.googleusercontent.com',
    iosBundleId: 'com.example.qcFirebaseFlutter.RunnerTests',
  );
}
